import './global.css';
import Navbar from './Navbar';
import SimpleParallax from './components/SimpleParallax';
import IOSOptimizer from './components/IOSOptimizer';
import ParallaxDebug from './components/ParallaxDebug';

export const metadata = {
  title: 'Welcome to user-web',
  description: 'Generated by create-nx-workspace',
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: 'cover',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="apple-touch-fullscreen" content="yes" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="theme-color" content="#000000" />
        <meta name="msapplication-TileColor" content="#000000" />
        <meta name="msapplication-tap-highlight" content="no" />
      </head>
      <body>
        <Navbar />
        <SimpleParallax />
        <IOSOptimizer />
        <ParallaxDebug />
        {children}
      </body>
    </html>
  );
}
