import './global.css';
<<<<<<< HEAD
import Navbar from './Navbar';
=======
>>>>>>> 13a80fa78934b14a45c1a7bd9b425b6115337a5c

export const metadata = {
  title: 'Welcome to user-web',
  description: 'Generated by create-nx-workspace',
};

<<<<<<< HEAD
export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: 'cover',
};

=======
>>>>>>> 13a80fa78934b14a45c1a7bd9b425b6115337a5c
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <head>
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="apple-touch-fullscreen" content="yes" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="theme-color" content="#000000" />
        <meta name="msapplication-TileColor" content="#000000" />
        <meta name="msapplication-tap-highlight" content="no" />
      </head>
      <body>
        <Navbar />
        {children}
      </body>
=======
      <body>{children}</body>
>>>>>>> 13a80fa78934b14a45c1a7bd9b425b6115337a5c
    </html>
  );
}
